### Create new user
POST http://localhost:8080/users
Content-Type: application/json

{
  "firstName": "Joan",
  "lastName": "Cabezas",
  "age": 19
}

### Update whole user data
PUT http://localhost:8080/users/1
Content-Type: application/json

{
  "id": 1,
  "firstName": "Joan Santiago",
  "lastName": "Cabezas",
  "age": 19
}

### Get users with simple authentication
GET http://localhost:8080/users
Authorization: Basic josancamon19 josancamon19123

### Delete user
DELETE http://localhost:8080/users/1

### Login (Get a JWT)
POST http://localhost:8080/login
Content-Type: application/json

{
  "id": 2
}
> {%client.global.set("auth_token", response.body.token);%}

### GET User by id
GET http://localhost:8080/users/2
Authorization: Bearer {{auth_token}}